#!/usr/bin/env php
<?php

namespace Application;

// load configuration
include __DIR__ . '/config.php';

// include composer packages
include realpath(__DIR__ . '/../vendor/autoload.php');

// set timezone
date_default_timezone_set(TIMEZONE);

// load and run the application
$app = new \dollmetzer\zzaplib\Console($config);
$app->run($argv);
